// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorPass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705203113_AddUserIdAndTimestampsToTrainingHistory")]
    partial class AddUserIdAndTimestampsToTrainingHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Pass")
                        .HasColumnType("text");

                    b.Property<string>("ResName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LocPass", (string)null);
                });

            modelBuilder.Entity("TrainingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("ClientUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_updated_at");

                    b.Property<string>("Health")
                        .HasColumnType("text")
                        .HasColumnName("health");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("KpAfter")
                        .HasColumnType("integer")
                        .HasColumnName("kpAfter");

                    b.Property<int?>("KpBefore")
                        .HasColumnType("integer")
                        .HasColumnName("kpBefore");

                    b.Property<int?>("LocalId")
                        .HasColumnType("integer")
                        .HasColumnName("local_id");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("Practise")
                        .HasColumnType("text")
                        .HasColumnName("practise");

                    b.Property<string>("RFaktor")
                        .HasColumnType("text")
                        .HasColumnName("rfaktor");

                    b.Property<DateTime>("ServerUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Sleep")
                        .HasColumnType("text")
                        .HasColumnName("sleep");

                    b.Property<string>("Train")
                        .HasColumnType("text")
                        .HasColumnName("train");

                    b.Property<DateOnly?>("TrainDate")
                        .HasColumnType("date")
                        .HasColumnName("trainDate");

                    b.Property<TimeOnly?>("TrainTime")
                        .HasColumnType("time")
                        .HasColumnName("trainTime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ServerUpdatedAt")
                        .HasDatabaseName("idx_training_history_server_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_training_history_user_id");

                    b.HasIndex("UserId", "LocalId")
                        .IsUnique()
                        .HasDatabaseName("idx_training_history_user_local_id");

                    b.ToTable("training_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
